### ISSUE TITLE
Javascript Warning shown in the app (android)

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-adaptor-sched#19] opened 2016-06-02 07:57 UTC
This happens when tapping on an event from the tile to see its details.
Related to issue #4 but a different error so opening this new issue
![screenshot_2016-06-01-09-51-19](https://cloud.githubusercontent.com/assets/1897507/15737786/50c7f804-28a8-11e6-991f-f05d4aca0bf0.png)

**Comment by isabelrios** [comment] 2016-06-02 08:22
That error happens using the debug build.
With nightly build, that is not shown, but the browser is not open, instead this screen is shown:
![screenshot_2016-06-01-10-16-51](https://cloud.githubusercontent.com/assets/1897507/15738448/99edb07a-28ab-11e6-8b18-ac0f56737250.png)

There, tapping on an event details launches the browser. Is this the new flow for seeing the event details?
Thanks!

**Comment by wilsonpage** [comment] 2016-06-02 13:36
This warning is a bug in the version of React-Native we're on. Upgrading to v0.26 will fix it, but requires that we update some on the APIs we use.

**Comment by wilsonpage** [comment] 2016-06-02 13:37
Turning off DEV mode hides the warning. This can be done by shaking the device and tapping 'developer settings' and unticking the checkbox.

**Comment by arcturus** [comment] 2016-06-06 18:09
Closing this, as it's not a bug in the magnet adaptor

**Closed as completed by arcturus** 2016-06-06 18:09 UTC
Labels: bug, P1
